name: DynRegionPerf
version: '${project.version}'
main: com.dynregionperf.DynRegionPerfPlugin
api-version: '1.20'
author: DynRegionPerf
description: Dynamic region performance optimization plugin for Paper/Folia servers
website: https://github.com/dynregionperf/DynRegionPerf

depend: []
softdepend: [PaperLib]

commands:
  perf:
    description: Main DynRegionPerf command
    usage: /perf <status|boost|profile>
    permission: dynperf.view
    permission-message: You don't have permission to use this command.

permissions:
  dynperf.view:
    description: Allows viewing performance status
    default: op
  dynperf.admin:
    description: Allows administrative performance commands
    default: op
